### ISSUE TITLE
Keeping this up to date with docker-plex

### ISSUE THREAD

**Issue by flungo** [timhaak/docker-plexpass#3]
What is the current strategy for keeping this up to date with the [docker-plex](https://github.com/timhaak/docker-plex) repository? Obviously there have been a lot of changes made to  docker-plex that need migrating. Could we look into automating the update of this repo?

I saw the [rockerfile branch](https://github.com/timhaak/docker-plex/tree/rockerfile) of docker-plex. I haven't used Rocker myself but is this a good option? Or would a scripted solution using continuous integration work better?

**Comment by timhaak** [comment]
Hi

I don't really have one at the moment. Currently copy paste.

I'm not a fan of the rocker file as I prefer using native features as it mean's anyone can build.

Having said that. What was nice about that branch was actually using and external build then push to docker hub.

So using build args we could have one dockerfile. Or with two dockerfiles.

Current docker hub doesn't support args as that would be the simplest but apparently its coming.

@kalbasit was the person who did most of that work.

Currently been stupidly busy so havant had time to even think about this stuff.

**Comment by timhaak** [comment]
Hi @neclimdul 

I did think about doing with your pull request method. 

Though it increased the size of the image as their would be a layer with the normal plex install in it.

The one option I was thinking was to use something like codeship or something similar to do builds with env build variables. Then have them pushed.

But time :)

Apparently hub.docker is going to be adding support at some point for the build env variables.

I might use yours a quick fix so I don't have to think about it till we come up with a better solution.

But let me think about it a bit first.

**Comment by neclimdul** [comment]
No rush, just put it out there in case it helped :)

**Comment by flungo** [comment]
With regard to cutting down the image size, one idea based on what @neclimdul suggests might be to use abstraction. Create a `plexbase` containing all dependencies and scripts and then `plex` and `plexpass` extend by installing the relevant version of Plex?

**Comment by neclimdul** [comment]
Ha! I actually had the same idea a couple days ago and have been playing with it here https://github.com/neclimdul/docker-plex

I setup a dockerhub build with tags and so far so good running the plex-pass tag on my media server. If you like it I'll open PR. Using the tags is quite a bit different from the current approach though so not sure how disruptive switching would be.

**Comment by bkuhl** [comment]
All GitLab repositories get free CI.  Though since this is already open source on GitHub, Travis-CI.org will provide free CI services.  I'm experienced with Travis-CI and would be willing to contribute to this.  I've setup several CI integrations where a new GitHub release automatically triggers a CI build ([see example](https://github.com/bkuhl/game-watcher/blob/master/.travis.yml)) which pushes a newly build docker container to DockerHub.

I'm not sure how applicable this would be with the Plex stuff... but I built an automated release pipeline for [Factorio](http://www.factorio.com).  There's a small microservice that watches for game updates and [updates the `master` branch's Dockerfile on a given repo](https://github.com/bkuhl/game-watcher/blob/master/app/Games/Factorio/Factorio.php#L39) with the new version/sha.

**Comment by timhaak** [comment]
It should now be working off the one repo only via a travis build for plex pass.

So closing this.

**Comment by flungo** [comment]
The README of this project should probably be updated to reflect that this is now deprecated and continued development of the plexpass image will take place on the plex repo.

**Comment by timhaak** [comment]
Damn. I actually had updated it and somehow forgot to do the merge. I've not merged and the readme points at the default repo now.
